### ISSUE TITLE
Syncplay Menu Fails to Open on 1.9 With Existing Group

### ISSUE THREAD

**Issue by ibrokemypie** [jellyfin/jellyfin-desktop#182]
**Describe the bug**
The syncplay menu fails to open when a group already exists on 1.9.

**To Reproduce**
1. Have someone create a syncplay group
2. Open the same show on jellyfin-mpv-shim
3. Click the syncplay menu item

**Expected behavior**
Syncplay menu opens

**Desktop (please complete the following information):**
 - OS: Macos
 - Version: 11.2.1

**Error Messages**
```
2021-03-21 17:28:31,639 [   ERROR] mpv-jsonipc: EventHandler caught exception from (<function PlayerManager.__init__.<locals>.menu_ok at 0x10d84fe50>, ()).
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/python_mpv_jsonipc.py", line 363, in run
    event[0](*event[1])
  File "/usr/local/lib/python3.9/site-packages/jellyfin_mpv_shim/player.py", line 254, in menu_ok
    self.menu.menu_action("ok")
  File "/usr/local/lib/python3.9/site-packages/jellyfin_mpv_shim/menu.py", line 247, in menu_action
    self.menu_list[self.menu_selection][1]()
  File "/usr/local/lib/python3.9/site-packages/jellyfin_mpv_shim/syncplay.py", line 624, in menu_action
    group_option_list.append((group["GroupName"], self.menu_join_group, group))
KeyError: 'GroupName'
```

**Comment by iwalton3** [comment]
Is this with a server running 10.7.0 or 10.6.4?

**Comment by ibrokemypie** [comment]
10.6.4, seems okay on 10.7 now, although group names seem to always be unknown

**Comment by iwalton3** [comment]
Yeah I dropped support for 10.6.4. SyncPlay was changed too much for support to be practical.

I am aware of the unknown name issue. I missed something obvious and it is fixed in master/pending release.
