### ISSUE TITLE
Shuffle button no longer works

### ISSUE THREAD

**Issue by Tuttles** [jellyfin/jellyfin-desktop#197]
**Describe the bug**
Since updating to the latest version, the Shuffle button doesn't do anything anymore.

**To Reproduce**
1. Open any series page
2. Click on the Shuffle button

**Expected behavior**
To play a random episode from the series.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2004 (OS Build 19041.867)

**Error Messages**
2021-03-26 17:35:29,445 [   DEBUG] event_handler: Handled Event Play: {'ItemIds': ['f96c46c641d45745c58958883e6b4537'], 'PlayCommand': 'PlayShuffle', 'ControllingUserId': '411d94a9d98b4d6da5ca04781ccefd61', 'ServerId': '737537fb7ebd48d2b25133e9ea68b395'}
2021-03-26 17:35:29,489 [   DEBUG] urllib3.connectionpool: http://192.168.1.86:8096 "GET /Users/411d94a9d98b4d6da5ca04781ccefd61/Items/f96c46c641d45745c58958883e6b4537 HTTP/1.1" 200 None
2021-03-26 17:35:29,491 [   DEBUG] event_handler: EventHandler::playMedia <jellyfin_mpv_shim.media.Media object at 0x0000019031D7EF08>
2021-03-26 17:35:29,491 [   DEBUG] media: Bandwidth: local=True, bitrate=None, force=False
2021-03-26 17:35:29,545 [   DEBUG] urllib3.connectionpool: http://192.168.1.86:8096 "POST /Items/f96c46c641d45745c58958883e6b4537/PlaybackInfo HTTP/1.1" 500 None
2021-03-26 17:35:29,546 [   ERROR] Jellyfin.jellyfin_apiclient_python.http: 500 Server Error: Internal Server Error for url: http://192.168.1.86:8096/Items/f96c46c641d45745c58958883e6b4537/PlaybackInfo
2021-03-26 17:35:29,546 [   ERROR] Jellyfin.jellyfin_apiclient_python.http: --[ 500 response ] 500 Server Error: Internal Server Error for url: http://192.168.1.86:8096/Items/f96c46c641d45745c58958883e6b4537/PlaybackInfo
2021-03-26 17:35:29,546 [   ERROR] jellyfin_mpv_shim.webclient_view: Exception on /mpv_shim_message [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "jellyfin_mpv_shim\webclient_view\__init__.py", line 246, in mpv_shim_message
  File "jellyfin_mpv_shim\event_handler.py", line 65, in handle_event
  File "jellyfin_mpv_shim\event_handler.py", line 101, in play_media
  File "jellyfin_mpv_shim\player.py", line 421, in play
  File "jellyfin_mpv_shim\media.py", line 253, in get_playback_url
  File "jellyfin_mpv_shim\media.py", line 213, in get_best_media_source
TypeError: 'NoneType' object is not subscriptable
2021-03-26 17:35:29,547 [    INFO] werkzeug: 127.0.0.1 - - [26/Mar/2021 17:35:29] "[35m[1mPOST /mpv_shim_message HTTP/1.1[0m" 500 -
2021-03-26 17:35:32,159 [    INFO] werkzeug: 127.0.0.1 - - [26/Mar/2021 17:35:32] "[37mPOST /mpv_shim_event HTTP/1.1[0m" 200 -

**Comment by iwalton3** [comment]
I'm honestly surprised it ever worked because I never implemented `PlayShuffle`. I wonder if the Jellyfin server was shuffling the files and then sending them to my client already shuffled.

For reference, the new version of the desktop app deals with the play requests directly.

**Comment by Tuttles** [comment]
That's interesting! Yes, it used to work fine I would hit shuffle and let it go for hours.

**Comment by iwalton3** [comment]
This will be fixed in the next release along with the play next and play last buttons in the menu.

**Comment by iwalton3** [comment]
This has been released.
