### ISSUE TITLE
AttributeError: mpv option does not exist

### ISSUE THREAD

**Issue by herrwusel** [jellyfin/jellyfin-desktop#198]
**Describe the bug**
I recently switched from plex to jellyfin and wanted to use mpv-shim as well. After using a local pip install I get an AttributeError.

**To Reproduce**
Launch `$ jellyfin-mpv-shim`

**Expected behavior**
jellyfin-mpv-shim does launch

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS

**Error Messages**
```
$ jellyfin-mpv-shim 
2021-03-31 07:32:13,859 [    INFO] conf: Loaded settings from json: /home/user/.config/jellyfin-mpv-shim/conf.json
2021-03-31 07:32:13,887 [    INFO] player: Using libmpv1 playback backend.
Traceback (most recent call last):
  File "/home/user/.local/bin/jellyfin-mpv-shim", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 71, in main
    from .player import playerManager
  File "/home/user/.local/lib/python3.8/site-packages/jellyfin_mpv_shim/player.py", line 1032, in <module>
    playerManager = PlayerManager()
  File "/home/user/.local/lib/python3.8/site-packages/jellyfin_mpv_shim/player.py", line 174, in __init__
    self._player = mpv.MPV(
  File "/home/user/.local/lib/python3.8/site-packages/mpv.py", line 820, in __init__
    _mpv_set_option_string(self.handle, k.replace('_', '-').encode('utf-8'), istr(v).encode('utf-8'))
  File "/home/user/.local/lib/python3.8/site-packages/mpv.py", line 133, in raise_for_ec
    raise ex(ec, *args)
AttributeError: ('mpv option does not exist', -5, (<MpvHandle object at 0x7fe7f04527c0>, b'scripts', b'/home/user/.local/lib/python3.8/site-packages/jellyfin_mpv_shim/mouse.lua'))
```

**Comment by iwalton3** [comment]
Get a build of MPV with Lua support compiled in or disable the config option `settings.menu_mouse` to disable mouse support in the menu.

**Comment by herrwusel** [comment]
Thanks! So the Ubuntu packaged mpv doesn't come with lua support?
