### ISSUE TITLE
Admin Dashboard and Profile Settings fail to open with new server update

### ISSUE THREAD

**Issue by lukaslindnermusic** [jellyfin/jellyfin-desktop#734]
**Describe the bug**
I am not sure if this issue is related to #733 but it also occurs after the latest update of the server to 10.9.8.
I can't open the Admin Dashboard, it just shows an empty screen on the following tabs:
Dashboard, General, Libraries (and everything in it), Playback (Transcoding, Resume and Streaming only, Trickplay see below), Devices, Live TV, DVR, Networking, API Keys, Logs, Plugins (and everything in it), Scheduled Tasks

The following pages work:
Activity, DLNA, Notifications (only shows a message that this was moved to the webhook plugin), Playback Reporting (which is a Plugin)

But there also are pages where the following error appears:

```
Unexpected Application Error!
Loading chunk 9971 failed. (error: http://192.168.178.2:8096/web/9971.ba466be3b8b68a4fb2b5.chunk.js)
ChunkLoadError: Loading chunk 9971 failed.
(error: http://192.168.178.2:8096/web/9971.ba466be3b8b68a4fb2b5.chunk.js)
    at Object.s.f.j (http://192.168.178.2:8096/web/runtime.bundle.js?9410c8e21a4e2de14aaa:1:46156)
    at http://192.168.178.2:8096/web/runtime.bundle.js?9410c8e21a4e2de14aaa:1:1410
    at Array.reduce (<anonymous>)
    at s.e (http://192.168.178.2:8096/web/runtime.bundle.js?9410c8e21a4e2de14aaa:1:1375)
    at Array.map (<anonymous>)
    at a (http://192.168.178.2:8096/web/90479.f1abe8ea645c1b17819c.chunk.js:1:58070)
    at Object.requireAsync (http://192.168.178.2:8096/web/90479.f1abe8ea645c1b17819c.chunk.js:1:30710)
    at _ (http://192.168.178.2:8096/web/7466.bundle.js?9410c8e21a4e2de14aaa:2:39457)
    at r.n.resolveAsync (http://192.168.178.2:8096/web/7466.bundle.js?9410c8e21a4e2de14aaa:2:41790)
    at r.n.loadAsync (http://192.168.178.2:8096/web/7466.bundle.js?9410c8e21a4e2de14aaa:2:41443)
```

The pages are:
Settings -> Profile
Admin Dashboard -> Users
Admin Dashbaord -> Playback -> Trickplay

These errors do not happen with Jellyfin Web.

**To Reproduce**
1. Update Server to latest version (10.9.8)
2. Open Jellyfin Media Player
3. Navigate to either the Admin Dashboard or the Profile Settings

**Expected behavior**
Well, the Dashboard or the Profile settings should appear :P 

**Screenshots**
<img width="2672" alt="Bildschirmfoto 2024-07-22 um 22 44 28" src="https://github.com/user-attachments/assets/98139cdb-da0b-49af-992b-5ef986d6ae86">
<img width="2672" alt="Bildschirmfoto 2024-07-22 um 22 45 34" src="https://github.com/user-attachments/assets/9e4820ed-6206-4c24-87b3-2d15aab6fb4d">

**Desktop (please complete the following information):**
 - OS: macOS with 3,8 GHz 8-Core Intel Core i7
 - Version: Ventura 13.6.6 (22G630)
 - Installation Method: Mac Intel dmg file (latest version: v1.11.1)

**Logs**
The logs only show these messages:
```
2024-07-22 22:48:38.865 [info] unknown @ 0 - JS: [viewContainer] resetting view cache
2024-07-22 22:48:38.868 [info] unknown @ 0 - JS: [getTheme] getting theme "%s" dark
2024-07-22 22:48:38.900 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:48:39.038 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 616 failed.
(error: http://192.168.178.2:8096/web/dashboard-dashboard-html.1cc5e3ccaea4ffd9100b.chunk.js)
2024-07-22 22:48:41.956 [info] unknown @ 0 - JS: Sending web socket message: KeepAlive
2024-07-22 22:48:41.958 [info] unknown @ 0 - JS: Received KeepAlive from server.
2024-07-22 22:48:54.329 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:48:54.341 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 44037 failed.
(error: http://192.168.178.2:8096/web/dashboard-devices-devices-html.eb5865f29eda668cbe8c.chunk.js)
2024-07-22 22:48:58.015 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:48:58.019 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 12481 failed.
(error: http://192.168.178.2:8096/web/livetvstatus-html.b5e322ca19e02a1055f0.chunk.js)
2024-07-22 22:48:59.264 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:48:59.269 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 90854 failed.
(error: http://192.168.178.2:8096/web/livetvsettings-html.1911150a7f69d6ca4569.chunk.js)
2024-07-22 22:49:00.345 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:49:00.349 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 19926 failed.
(error: http://192.168.178.2:8096/web/dashboard-networking-html.5c28e424868a295e8e72.chunk.js)
2024-07-22 22:49:01.227 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:49:01.232 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 8512 failed.
(error: http://192.168.178.2:8096/web/dashboard-apikeys-html.c27142bb01890bd40def.chunk.js)
2024-07-22 22:49:02.181 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:49:02.184 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 70163 failed.
(error: http://192.168.178.2:8096/web/dashboard-logs-html.69910be2b6182bc346dd.chunk.js)
2024-07-22 22:49:04.007 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:49:04.012 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 64718 failed.
(error: http://192.168.178.2:8096/web/dashboard-plugins-installed-index-html.3b1ec279124e7b14306d.chunk.js)
2024-07-22 22:49:05.144 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:49:05.149 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 94327 failed.
(error: http://192.168.178.2:8096/web/dashboard-plugins-available-index-html.0e8d3e20b404082ed477.chunk.js)
2024-07-22 22:49:05.644 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:49:05.648 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 46326 failed.
(error: http://192.168.178.2:8096/web/dashboard-plugins-repositories-index-html.7423bdbb1d75ea8aca1a.chunk.js)
2024-07-22 22:49:06.248 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:49:06.252 [info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 21513 failed.
(error: http://192.168.178.2:8096/web/dashboard-scheduledtasks-scheduledtasks-html.f42adcfbb4c0ebcdc850.chunk.js)
2024-07-22 22:49:07.283 [info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
2024-07-22 22:49:07.285 [info] unknown @ 0 - JS: Requesting http://192.168.178.2:8096/web/configurationpage?name=user_report
```

**Comment by lukaslindnermusic** [comment]
(the chunk that failed to load is different at each page)

**Comment by lukaslindnermusic** [comment]
If I open a dashboard tab that works, and then click away to one that does not load at all, the content of the previous tab that worked stays there.

**Comment by polyzen** [comment]
Similar issue on jellyfin-android, but at least Scheduled Tasks seems to work there still.

**Comment by polyzen** [comment]
jellyfin-web 10.9.8 doesn't seem to have these issues.

**Comment by ftc2** [comment]
same issue for me

**Comment by tomkv** [comment]
I had tthe same problem after updating the server (including updating to 10.9.8). Deleting the cache (`~/Library/Caches/Jellyfin Media Player` on Mac, something similar must exist on other platforms) helped.

**Comment by lukaslindnermusic** [comment]
ok. I was just trying to delete the cache like @tomkv suggested, but before I did that I just checked back on the error. 
I realized, that it now suddenly worked as it should. 
Maybe my cache was deleted automatically? curious, that one :P

**Comment by polyzen** [comment]
On July 24, 2024 6:20:16 AM EDT, lukaslindnermusic ***@***.***> wrote:
> ok. I was just trying to delete the cache like @tomkv suggested, but before I did that I just checked back on the error. 
> I realized, that it now suddenly worked as it should. 
> Maybe my cache was deleted automatically? curious, that one :P 
> 

Haven't checked JMP yet, but jellyfin-android seems to be working fine now as well. Good catch, guys!

My maintenance scheduled tasks (apart from "clean up collections and playlists") have run since I had last checked.

https://github.com/jellyfin/jellyfin-media-player/issues/733 seems to be resolved as well.

--
Best,
Daniel <https://danielcapella.com>

**Comment by andrewrabert** [comment]
Should be fixed as of at least v2.0, but feel free to reopen if not.
